// Enum de tipos de eventos de analytics
// Deve estar sincronizado com o enum AnalyticsEventType no backend
export enum AnalyticsEventType {
  // Sessões de Estudo
  STUDY_SESSION_STARTED = 'STUDY_SESSION_STARTED',
  STUDY_SESSION_COMPLETED = 'STUDY_SESSION_COMPLETED',
  STUDY_SESSION_PAUSED = 'STUDY_SESSION_PAUSED',
  STUDY_SESSION_STOPPED = 'STUDY_SESSION_STOPPED',

  // Assuntos
  TOPIC_CREATED = 'TOPIC_CREATED',
  TOPIC_UPDATED = 'TOPIC_UPDATED',
  TOPIC_DELETED = 'TOPIC_DELETED',
  TOPIC_VIEWED = 'TOPIC_VIEWED',

  // Flashcards
  FLASHCARD_CREATED = 'FLASHCARD_CREATED',
  FLASHCARD_REVIEWED = 'FLASHCARD_REVIEWED',
  FLASHCARD_DELETED = 'FLASHCARD_DELETED',

  // Sessões Agendadas
  SESSION_SCHEDULED = 'SESSION_SCHEDULED',
  SESSION_COMPLETED = 'SESSION_COMPLETED',
  SESSION_CANCELLED = 'SESSION_CANCELLED',

  // Hábitos
  HABIT_CREATED = 'HABIT_CREATED',
  HABIT_COMPLETED = 'HABIT_COMPLETED',
  HABIT_UPDATED = 'HABIT_UPDATED',
  HABIT_DELETED = 'HABIT_DELETED',

  // Navegação
  PAGE_VIEWED = 'PAGE_VIEWED',
  FEATURE_ACCESSED = 'FEATURE_ACCESSED',

  // Interações
  BUTTON_CLICKED = 'BUTTON_CLICKED',
  FORM_SUBMITTED = 'FORM_SUBMITTED',
  SEARCH_PERFORMED = 'SEARCH_PERFORMED',
}

